name: macOS CI

on:
  push:
    branches: [ "sdl3-cmake" ]

jobs:
  macos-arm64-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake --install build
        mkdir -p ./build/dist
        cp -R ./build/iris.app ./build/dist
    - uses: actions/upload-artifact@v4
      with:
        name: iris-macos-arm64-latest
        path: ./build/dist
