name: Ubuntu CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Build and pack Iris
      run: |
        git fetch --all --tags
        cmake -S . -B build
        cmake --build build -j8
        sudo cmake --install build
        mkdir dist
        mv ./build/iris ./dist
        mkdir appimage
        mv ./build/*.AppImage ./appimage
    - uses: actions/upload-artifact@v4
      with:
        name: iris-ubuntu-latest
        path: ./dist
    - uses: actions/upload-artifact@v4
      with:
        name: iris-ubuntu-appimage-latest
        path: ./appimage
